name: Notifications in Telegram

on:
  pull_request:
    types:
      - opened
      - review_requested
      - closed
    

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Github Telegram Notifier
        # You may pin to the exact commit or the version.
        # uses: EverythingSuckz/github-telegram-notify@11cbbc4c9284459d289584e9da5c24e0bdfc07b9
        uses: EverythingSuckz/github-telegram-notify@v1.1.2
        with:
          # A bot token for sending the github commit updates to a chat. You may create one my sending `/newbot` to [@BotFather](https://telegram.dog/BotFather)
          bot_token: ${{ secrets.TG_NOTIFY_BOT_TOKEN }}
          # The ID of the chat where you want the bot to send the message
          chat_id: ${{ secrets.TG_NOTIFY_CHAT_ID }}
          # The ID of the topic where you want to receive the notifications.
          topic_id: ${{ secrets.TG_NOTIFY_TOPIC_ID }}
                
